name: CD Dev Deployment

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.https://api.render.com/deploy/srv-d8shc2r7uimc738cppv0?key=NeyjchWa9YU }}

      - name: Confirm Deployment
        run: echo "Deployment to DEV triggered at $(date)"
