name: CD Production Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.https://api.render.com/deploy/srv-d8sheq7avr4c73fq46b0?key=i40HMqIil5Y }}

      - name: Confirm
        run: echo "Deployment to PROD triggered at $(date)"
