name: CD Staging Deployment

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.https://api.render.com/deploy/srv-d8shdjm7r5hc73fgsp1g?key=mCiW5Og7G_o }}

      - name: Confirm
        run: echo "Deployment to STAGING triggered at $(date)"
